name: Build

on:
  push:

env:
  TARGET: LumiRouter.ota
  BUILD_DIR: build
  ARTIFACT_DIR: build/src
  SDK_DIR: sdk
  SDK_COMMIT: 78b9f41cedfdffef188ccc79fb47709274c354e6
  TOOLCHAIN_DIR: toolchain

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get toolchain
        run: |
          mkdir -p ${{ env.TOOLCHAIN_DIR }} && \
          wget https://github.com/openlumi/BA2-toolchain/releases/download/20201219/ba-toolchain-20201219.tar.bz2 -O - | tar -jx -C ${{ env.TOOLCHAIN_DIR }} && \
          mv ${{ env.TOOLCHAIN_DIR }}/ba-toolchain/* ${{ env.TOOLCHAIN_DIR }} && \
          rm -rf ${{ env.TOOLCHAIN_DIR }}/ba-toolchain
      - name: Get SDK
        run: |
          mkdir -p ${{ env.SDK_DIR }} && \
          cd ${{ env.SDK_DIR }} && \
          wget https://github.com/devbis/JN-SW-4170/archive/${{ env.SDK_COMMIT }}.zip -O sdk.zip && \
          unzip sdk.zip && \
          rm sdk.zip && \
          cd - && \
          mv ${{ env.SDK_DIR }}/JN-SW-4170*/* ${{ env.SDK_DIR }} && \
          rm -rf ${{ env.SDK_DIR }}/JN-SW-4170* \
      - name: Install xmltodict and pycryptodome
        run: pip3 install xmltodict pycryptodome
      - name: CMake
        id: configure
        run: |
          mkdir -p build && cd build
          cmake -DTOOLCHAIN_PREFIX=$(realpath ../${{ env.TOOLCHAIN_DIR }}) -DSDK_PREFIX=$(realpath ../${{ env.SDK_DIR }}) ..
      - name: make
        id: make
        run: |
          cd build && make -j$(($(nproc)+1)) ${{ env.TARGET }} && rm src/*tmp.bin
          echo "::set-output name=status::success"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        if: steps.make.outputs.status == 'success' && !cancelled()
        with:
          # Artifact name
          name: firmwares.zip
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ${{ env.ARTIFACT_DIR }}/*.bin
            ${{ env.ARTIFACT_DIR }}/*.ota

      - name: Generate release tag
        id: tag
        if: github.ref == 'refs/heads/master' && !cancelled()
        run: |
          echo "::set-output name=release_tag::${GITHUB_SHA::4}--$(date +"%Y%m%d-%H%M")"
          echo "::set-output name=status::success"

      - name: Create changelog
        id: create_changelog
        if: steps.tag.outputs.status == 'success' && !cancelled()
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyLastTag: true
          stripHeaders: true

      - name: Upload firmware to release
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body: ${{ steps.create_changelog.outputs.changelog }}
          files: |
            ${{ env.ARTIFACT_DIR }}/*.bin
            ${{ env.ARTIFACT_DIR }}/*.ota
          prerelease: true
